# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Iten', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notificacao', 'verbose_name_plural': 'Notificacoes'},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cliente'),
        ),
    ]
