# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-20 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180118_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.CharField(blank=True, max_length=300, null=True)),
                ('id_pedido', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_total', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cor', models.CharField(blank=True, choices=[('NAVY', '#001F3F'), ('AZUL', '#3c8dbc'), ('AZUL-CLARO', '#00c0ef'), ('TURQUESA', '#39CCCC'), ('VERDE', '#00a65a'), ('ROXO', '#605ca8'), ('AMARELO', '#f39c12'), ('LARANJA', '#ff851b'), ('VERMELHO', '#f56954'), ('ROSA', '#D81B60'), ('CINZA', '#d2d6de'), ('PRETO', '#111111')], max_length=100, null=True)),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FormaPagamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('eminente', models.CharField(blank=True, max_length=300, null=True)),
                ('razao', models.CharField(blank=True, max_length=300, null=True)),
                ('valor', models.CharField(blank=True, max_length=300, null=True)),
                ('data', models.CharField(blank=True, max_length=300, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cor', models.CharField(blank=True, choices=[('NAVY', '#001F3F'), ('AZUL', '#3c8dbc'), ('AZUL-CLARO', '#00c0ef'), ('TURQUESA', '#39CCCC'), ('VERDE', '#00a65a'), ('ROXO', '#605ca8'), ('AMARELO', '#f39c12'), ('LARANJA', '#ff851b'), ('VERMELHO', '#f56954'), ('ROSA', '#D81B60'), ('CINZA', '#d2d6de'), ('PRETO', '#111111')], max_length=100, null=True)),
                ('forma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FormaPagamento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
