# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-20 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_entrada_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saida',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
